services:
  - type: web
    name: raw-io-backend
    runtime: python
    rootDir: backend/fast_end_points
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn req:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
